apiVersion: v1
kind: Service
metadata:
  name: message-processor-service
spec:
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30082
  selector:
    app: message-processor-service