micronaut.server.port=8082

arangodb.host=arangodb
#arangodb.host=localhost
arangodb.port=8529
arangodb.user=root
arangodb.password=password
arangodb.database=messages

kafka.bootstrap.servers=kafka:9092
#kafka.bootstrap.servers=localhost:9092

kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka.topic.messages=messages-topic
kafka.group-id.processor=message-processor-group

export.secret-token=secretToken1234

