
micronaut.server.port=8081



datasources.default.url=jdbc:postgresql://postgres:5432/messages
#datasources.default.url=jdbc:postgresql://localhost:5432/messages
datasources.default.username=user
datasources.default.password=password
datasources.default.driver-class-name=org.postgresql.Driver

jpa.default.properties.hibernate.hbm2ddl.auto=update

kafka.bootstrap.servers=kafka:9092
#kafka.bootstrap.servers=localhost:9092
kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
kafka.topic.messages=messages-topic
kafka.group-id.processor=message-processor-group


#Swagger
micronaut.openapi.enabled=true
micronaut.openapi.views.spec=swagger-ui.enabled=true
micronaut.openapi.info.title=Message Saver API
micronaut.openapi.info.version=1.0
micronaut.openapi.info.description=????????

micronaut.router.static-resources.swagger.paths=classpath:META-INF/swagger
micronaut.router.static-resources.swagger.mapping=/swagger/**

micronaut.application.name=message-saver-service